[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9000

[emailConfig]
authcode = "omhvljsrtuflcjde"
email = "3332366752@qq.com"

[redisConfig]
host = "192.168.10.128"
port = 6379
db = 0
password = "123456"

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
databaseName = "GopherAI"
charset =  "utf8mb4"

[jwtConfig]
expire_duration= 8760
issuer= "zzzzzbhhh"
subject= "GopherAI"
key= "GopherAI-v1"

[rabbitmqConfig]
host= "127.0.0.1"
port= 5672
username= "guest"
password= "guest"
vhost= "/"